### ISSUE TITLE
It's Crashing the game upon entering a door

### ISSUE THREAD

**Issue by C4RL0SPR** [bo4p5687/PE-Custom-Script#2]
I have two plugging's that use the word pbCancelVehicle and it crashes the game upon entering a door, I decide to remove the other plugging and it still crashes the game, I don't think is has to do with two plugging's calling the same command, but I will added anyway.

![image](https://user-images.githubusercontent.com/53522176/158269181-f9b7a0f9-a8b3-4f8c-a372-be39925dbd61.png)

**Comment by C4RL0SPR** [comment]
If I remove all the code calling the pbCancelVehicles the game stops crashing, but the walking stays with the attributes of the bike.

**Comment by bo4p5687** [comment]
Your other files used `pbCancelVehicle` and these defs aren't the same.
* Example:
 pbCancelVehicle(`a`) and pbCancelVehicle(1)
-> It's example, you can check your script like this.
