### ISSUE TITLE
Summary contest page

### ISSUE THREAD

**Issue by Umahyane** [bo4p5687/PE-Custom-Script#3]
Hi! I'm a biologist and I'm working in a new game where people could learn about zoology.
I love your plugins about contests but I don't know how to include a new page about contest moves in the summary
I'm trying to do it but I'm a noob in programming :(
Could you help me please? ó.ò 
Do you know how to do it?
Thank you in advance

**Comment by bo4p5687** [comment]
Hmm! Now, I don't have time to write script or instructions, but I can suggest you use these scripts `SetContestMoves.r_move` and `SetContestMoves.r_func(name)`.

* Explain:
1. SetContestMoves.r_move
-> This calls move contest's data
2. SetContestMoves.r_func(name)
-> This calls `element` of move contest.
 -> These `elements` are: :id_number, :id, :name, :type, :heart, :jam, :function and :description
You can replace name in () into one of `elements` above.

Ok, now, how to add in summary? You should read FL's script, there is one script which FL wrote has guide in this.

Good luck!

**Comment by Umahyane** [comment]
Thank you very much! I'll try it
